✨ [NFT] Add notification templates & refactoring
likecoin/likecoin-edm pull request #34
Opened 2023-02-08 17:08 UTC by nwingt

Purchase/collect/buy
<img width="600" alt="image" src="https://user-images.githubusercontent.com/17264716/217601358-8c166d1b-c7d6-4f1d-8067-c3668fc72fc1.png">

Transfer
<img width="600" alt="image" src="https://user-images.githubusercontent.com/17264716/217601425-423ec829-ad35-4006-9767-fe1ffc96fcc4.png">

2023-02-08 18:53 UTC, williamchong requested changes

2023-02-08 18:53 UTC, williamchong commented on src/i18n/translations/en.json
> +  "nft_notification_purchase_content": "You have collected <nft>NFT_TITLE</nft>, please <details>click here</details> to view the details.",
`purchase`(or sale) notifications are used when user (creator) sold a WNFT (ideally price > thersold) they receive an email, so the content here is inverted

2023-02-09 01:32 UTC, nwingt commented
# English

Purchase/collect/buy
<img width="601" alt="image" src="https://user-images.githubusercontent.com/17264716/217692199-42a4a2db-d10b-4f50-b932-a72554e7c888.png">

Transfer
<img width="601" alt="image" src="https://user-images.githubusercontent.com/17264716/217692242-bede7c33-d51d-49f6-942c-34a6e05b1a36.png">

2023-02-09 15:21 UTC, williamchong approved these changes

2023-02-13 03:27 UTC, merged