Support localization and add monthly report templates
likecoin/likecoin-edm pull request #4
Opened 2021-01-28 03:25 UTC by nwingt

2021-01-29 18:25 UTC, williamchong requested changes

2021-01-29 18:25 UTC, williamchong commented on src/components/avatar.tsx
> +          alt=""
alt could be `avatar of ${likerID}`

2021-02-03 14:10 UTC, williamchong requested changes
Seems all field are optional field in the type definition, not sure if good pratice

2021-02-03 14:10 UTC, williamchong commented on src/components/avatar.tsx
> +          alt={displayName || likerID}
`LikerID` and `displayName` are both optional props, would guarding this with `''` or making `LikerID` required better?

2021-02-03 14:10 UTC, williamchong commented on src/templates/reports/monthly/writer/index.tsx
> +                key={i}
What is the problem of using `url` here?

2021-02-04 18:23 UTC, williamchong approved these changes

2021-02-06 13:29 UTC, williamchong requested changes

2021-02-06 13:29 UTC, williamchong commented on src/components/cta-sponsor-link.tsx
> +              {`${LIKER_LAND_ROOT}/${likerID}/civic`}
Should this be a link wrapped in utm?

2021-02-06 13:29 UTC, williamchong commented on src/components/cta-sponsor-link.tsx
> +                <Link href={`${LIKER_LAND_ROOT}/creators`}>{text}</Link>
Should this be wrapped in utm?

2021-02-06 16:49 UTC, nwingt commented on src/components/cta-sponsor-link.tsx
> +                <Link href={`${LIKER_LAND_ROOT}/creators`}>{text}</Link>
Yes

2021-02-06 16:50 UTC, nwingt commented on src/components/cta-sponsor-link.tsx
> +              {`${LIKER_LAND_ROOT}/${likerID}/civic`}
This is for display only, not link

2021-02-08 06:49 UTC, williamchong approved these changes

2021-02-09 14:21 UTC, williamchong approved these changes

2021-02-26 06:53 UTC, closed without merging